Ot99 53 form
alkemyTech/OT-99-Server pull request #11
Opened 2021-10-28 02:32 UTC by ingrid-inga

![Contact](https://user-images.githubusercontent.com/75276647/139175979-540a8b1b-d99f-4ac5-8efc-55c99e5d32e4.png)
![ContactRepo](https://user-images.githubusercontent.com/75276647/139175998-105fed9d-9e3e-4b3f-a8df-cbac2cf24cd6.png)

Model and repository.

2021-10-31 21:29 UTC, nicolascareri requested changes

2021-10-31 21:29 UTC, nicolascareri commented on pom.xml
> -<?xml version="1.0" encoding="UTF-8"?>
OJO CON ESTO. Aca dice que eliminaste el POM. si mergeo esto se podria romper

2021-10-31 21:29 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/ContactService.java
> +public class ContactService {
Varias cosas, cuando te dice crear el servicio  se refiere a que lo crees vacio sin ningun metodo, tal cual hiciste en el repository.
Por otro lado el servicio SIEMPRE debe ser una interfaz de la cual se implementa una clase, y esa clase que implementa la interfaz es la que lleva la anotacion "@Service"

2021-10-31 23:21 UTC, ingrid-inga commented on src/main/java/com/alkemy/ong/service/ContactService.java
> +public class ContactService {
Hola!. la anotación service estaba en la línea 14. ¡Muchas Gracias por la revisión! =)
Lo modifiqué, sin embargo no me permite ejecutar push. Adjunto captura.
![Updated_Service](https://user-images.githubusercontent.com/75276647/139604578-b511207b-2068-4dc5-8f6a-337cea87a794.png)
![Rejected_push](https://user-images.githubusercontent.com/75276647/139604600-e4fc1e48-534d-4b2a-b575-2bf345740bb0.png)

2021-10-31 23:52 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/ContactService.java
> +public class ContactService {
es porque tenes conflictos, te vas a tener que hacerte un pull de master y resolverlos

2021-11-01 02:42 UTC, ingrid-inga commented on src/main/java/com/alkemy/ong/service/ContactService.java
> +public class ContactService {
Después del pull y resolución de conflictos. Me sigue saliendo el mismo mensaje de rejected; entre las soluciones que encontré son:

1.- git push -f origin OT99-53-Form
2.- crear una nueva rama

Te consulto a fin de evitar inconvenientes. ¡Muchas Gracias!

2021-11-01 19:11 UTC, nicolascareri requested changes

2021-11-01 19:11 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/config/SwaggerConfig.java
> +public class SwaggerConfig {
Todavia me sigue apareciendo. Habria que revisarlo

2021-11-01 19:11 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/ContactService.java
> +public class ContactService {
Falta todavia crear la interfaz y la implementacion

2021-11-02 00:32 UTC, ingrid-inga commented
![IContactService](https://user-images.githubusercontent.com/75276647/139760190-b05ab341-eeba-4ecd-92e6-216e78a556f9.png)

Archivos solicitados agregados + 1 archivo eliminado(SwaggerConfig).  Agradezco puedas confirmarme si es necesario eliminar el archivo "pom.xml" del presente PR. ¡Muchas Gracias!

2021-11-02 15:51 UTC, nicolascareri requested changes

2021-11-02 15:51 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/abstraction/IContactService.java
> +public interface IContactService {
No hace falta agregar el "I" adlenate del nombre del archivo porque van a estar en packetes diferntes con el servicio. Asi que dejale solamente ContactService. Otra cosa, estas interfaces deberian estar sueltas en el package "service"

2021-11-02 15:51 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/ContactServiceImpl.java
> +package com.alkemy.ong.service;
las implementaciones deberian ir en un package "impl" dentro del package "service"

2021-11-02 15:51 UTC, nicolascareri commented on pom.xml
> +
Esto habria que sacarlo tambien

2021-11-02 22:13 UTC, closed without merging