OT99-24: register user
alkemyTech/OT-99-Server pull request #13
Opened 2021-10-28 23:07 UTC by aguspecuch

- **STATUS 200**: show successful registration.

![200ok](https://user-images.githubusercontent.com/79877290/139345174-72de52a3-bca2-45a9-a616-527744d1544e.png)

_Database evidence:_

![prueba](https://user-images.githubusercontent.com/79877290/139345222-2ee6676a-9318-4dfd-a9ab-0d4c4851a128.png)

- **STATUS 400**: invalid first name.

![500name](https://user-images.githubusercontent.com/79877290/139345728-e65e3509-df6f-4184-b1b6-994765a66878.png)

- **STATUS 400**: invalid last name.

![500lastname](https://user-images.githubusercontent.com/79877290/139345758-57763d20-e11e-49bc-adec-3e30f8e63bac.png)

- **STATUS 400**: invalid email.

![500invalidemail](https://user-images.githubusercontent.com/79877290/139345800-4893a3fe-f252-4824-a123-b1273bbe62bb.png)

- **STATUS 400**: email already registered.

![500email](https://user-images.githubusercontent.com/79877290/139345861-995b8467-edef-4a92-a317-843c030273be.png)

- **STATUS 400**: invalid password.

![500invalidpasword](https://user-images.githubusercontent.com/79877290/139345916-a1d42726-ee19-426f-b795-2e4c39d2db4c.png)

- **STATUS 400**: multiple errors.

![500multipleerrors](https://user-images.githubusercontent.com/79877290/139346021-2717bf8b-d1d4-4b36-afc9-de70014b368b.png)

2021-10-31 21:47 UTC, nicolascareri requested changes

2021-10-31 21:47 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/AuthenticationController.java
> +        if (results.hasErrors()) {
No deberiamos incluir logica en el controller, preferentemente habria que llamar a un metodo del servicio que haga internamente todo esto

2021-10-31 21:47 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/RoleService.java
> +public class RoleService {
El servicio SIEMPRE debe ser una interfaz y tiene que tener una clase que la implemente y esta misma es la que llevaria la anotacion "@Service"

2021-10-31 21:47 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/UserService.java
> +public class UserService {
Lo mismo que te comente en RoleService

2021-11-01 19:17 UTC, nicolascareri requested changes

2021-11-01 19:17 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/imp/IBaseService.java
> +public interface IBaseService <E, ID>{
La estandarizacion de los nombres de los servicios suele ser la siguiente. Voy a ejemplificar con este caso.
La interfaz se llamaria UserService y se ubicaria en el package service, y por otro lado la clase se deberia llamar UserServiceImpl que se encuentra en el package impl, y implementa la interfaz mencionada anteriormente

2021-11-01 19:17 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/UserService.java
> +    public List<String> showRegisterErrors(BindingResult results) {
para que es esto de los errores? Por lo que entiendo no haria falta

2021-11-01 19:17 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/UserService.java
> +public class UserService implements IBaseService<User, Long> {
No tiene sentido hacer una interfaz generica, si en la interfaz no declaras los metodos. De todas formas la mejor a la hora de implementar las diferentes capas de la arquitectura que usamos es que cada servicio de cada modulo tenga su interfaz. Es decir que UserServiceImpl implementa UserService y por otrolado RoleServiceImpl implemente RoleService. Si tenes dudas avisame y lo charlamos

2021-11-01 19:29 UTC, aguspecuch commented on src/main/java/com/alkemy/ong/service/UserService.java
> +    public List<String> showRegisterErrors(BindingResult results) {
Me habias dicho en la correccion anterior que pase esa logica del controller al service asi que ahi esta 👆

2021-11-01 19:35 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/UserService.java
> +    public List<String> showRegisterErrors(BindingResult results) {
Sisi, ya se que esto estaba en el controller pero sigo sin entender cual es la finalidad. No me parece necesario.

2021-11-01 19:39 UTC, aguspecuch commented on src/main/java/com/alkemy/ong/service/UserService.java
> +    public List<String> showRegisterErrors(BindingResult results) {
Es para que devuelva todo los errores que haya cuando se intente registrar un usuario

2021-11-01 19:59 UTC, nicolascareri commented
@aguspecuch tenes conflictos en el pom.xml

2021-11-02 15:56 UTC, nicolascareri requested changes

2021-11-02 15:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/AuthenticationController.java
> +    UserServiceImpl userService;
Te quedo todo el PR impecable, muy bueno lo de las excepciones la verdad todo muy prolijo.

El unico cambio que tendrias que hacer es que aca tenes que hacer un autowired del UserService, osea vos aca usas la interfaz e internamente java cuando le pedis los metodos a la intefaz va a buscar una implementacion. Ademas si el dia de mañana hacemos otra implementaicon del servicio, no tenemos que cambiar el controller y todo seguiria funcionando igual

2021-11-02 15:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/request/UserRegisterRequest.java
> +package com.alkemy.ong.model.request;
Esto lo pondria en un package aparte de los model, porque esto esta mas asociado a la capa del cotnroller que del model. Podria ir dentro de un package "request" dentro del cotnroller, o podria ir en un package "dto" a la misma altura que los package de las capas

2021-11-02 15:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/response/UserRegisterResponse.java
> +package com.alkemy.ong.model.response;
Aca habria que hacer lo mismo que el comentario de arriba

2021-11-03 18:40 UTC, nicolascareri approved these changes

2021-11-03 18:46 UTC, merged