Ot99 15 add organization entity and repo
alkemyTech/OT-99-Server pull request #14
Opened 2021-10-29 20:15 UTC by TomasFogwill

**Summary**

1. Added Organization entity
2. Added Organization repository

**Evidence**
sql: show tables;
![evicence](https://user-images.githubusercontent.com/83930746/139496206-e66ff6ac-6bdc-47fa-ac99-75e56b22d3d4.png)
sql: describe organizations;
![evicence1](https://user-images.githubusercontent.com/83930746/139496266-1fe69298-7a0e-4685-8636-fd984a432b0f.png)
![evidence2](https://user-images.githubusercontent.com/83930746/139496349-7935a699-4219-4130-aefd-a7b7a2b7e27a.png)

2021-10-31 21:48 UTC, nicolascareri requested changes

2021-10-31 21:48 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/Organization.java
> +@Table(name = "organizations")
El nombre de la tabla no deberia ser plural, deberia ser en singular como la entidad. En este caso como la entidad y la tabla se van a terminar llamando igual, con la anotacion "@Entity" ya basta porque te crea una tabla con el mismo nombre, asi uqe deberiamos remover "@Table"

2021-11-01 13:38 UTC, TomasFogwill commented on src/main/java/com/alkemy/ong/model/Organization.java
> +@Table(name = "organizations")
Nico, concuerdo con lo que decís, me parece un nombre más apropiado, y eso implicaría remover la anotación. Pero acá en en el tiquet justamente aclara lo del nombre, por eso lo hice así. Si aún así te parece que no corresponde, lo cambio.
![ssss](https://user-images.githubusercontent.com/83930746/139680022-381f0727-3571-41a0-8ad3-cfa1373f6595.png)

2021-11-01 19:25 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/Organization.java
> +@Table(name = "organizations")
Hacelo en singular

2021-11-01 21:45 UTC, nicolascareri approved these changes

2021-11-02 15:58 UTC, nicolascareri requested changes

2021-11-02 15:58 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/Organization.java
> +@SQLDelete(sql = "UPDATE organizations SET is_deleted=true WHERE id=?")
Ahora que cambiamos el nombre de la entidad habria que cambiar el nombre de este update no?

2021-11-03 18:46 UTC, nicolascareri approved these changes

2021-11-03 18:47 UTC, merged