Ot99 31 jwt logic
alkemyTech/OT-99-Server pull request #16
Opened 2021-10-29 22:02 UTC by Stdela

- Added Jwt logic : Pr made in order to _obtain code review_
- included following classes:
1. JwtAuthenticationEntryPoint
2. JwtResponse
3. JwtTokenUtil
- Added basic configuration
- Created **auth controller** that returns a token
![image](https://user-images.githubusercontent.com/80407833/139506119-ea54d9ec-bc30-48dd-aa46-689962547d6f.png)
![image](https://user-images.githubusercontent.com/80407833/139506189-65715634-db1e-4e73-bf2c-1b1a4f0ab581.png)

2021-10-31 21:56 UTC, nicolascareri requested changes

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/Controller/UserController.java
> + * @author delam
delam??

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/Controller/UserController.java
> +@CrossOrigin
Esto no hace falta

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/Controller/UserController.java
> +    public ResponseEntity<?> registerUser(@RequestBody Users appUser) {
Esto esta no esta bien porque la historia no te esta pidiendo endpoints, de hecho estan los ticket correspondiente para el login y el register. Esta clase la deberiamos sacar del pull request

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +                .and().exceptionHandling().authenticationEntryPoint(jwtAuthenticationEntryPoint)
esta linea esta demas me parece, en conjunto con la clase que creaste arriba

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/filter/JwtAuthenticationEntryPoint.java
> +public class JwtAuthenticationEntryPoint implements AuthenticationEntryPoint {
Esto no estaria entiendo para que sirve pero esta de mas, no es necesario.

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/filter/JwtResponse.java
> +public class JwtResponse implements Serializable {
Esto tambien estaria demas porque al no tener controller no te corresponde crear DTO en esta historia

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/filter/JwtTokenUtil.java
> +                .setExpiration(new Date(System.currentTimeMillis() + 1000 * 60 * 60 * 10))
La expiracion no deberia estar hardcodeada, habria que pasarlo al application properties

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +                .antMatchers("/auth/sign_up", "/auth/login").permitAll()
Aca se puede crear un arreglo que se llame "PUBLIC_URLS" y ahi adentro vamos agregrando todas las URLS entonces no tocamos esta linea todo el tiempo cada vez que queremos agregar URLS publicas, queda mas legible y modularizado

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
Esto para que es? No lo veo necesario

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +//        http.addFilterBefore(jwtRequestFilter, UsernamePasswordAuthenticationFilter.class);
Que vamos a hacer con esto? Esperar que mergee lo de pablo y despues esto?

2021-10-31 21:56 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/filter/JwtTokenUtil.java
> +///COORDINADO CON PABLO
Estos comentarios no deberian estar en el codigo

2021-10-31 22:26 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +//        http.addFilterBefore(jwtRequestFilter, UsernamePasswordAuthenticationFilter.class);
no puedo mergear lo de pablo porque tiene cosas de este PR

2021-11-01 14:17 UTC, Stdela commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
Tenía entendido que configureGlobal era lo que nos permitía autorizar a nuestra clase UserDetails, mala mía!

2021-11-01 14:17 UTC, Stdela commented on src/main/java/com/alkemy/ong/filter/JwtTokenUtil.java
> +                .setExpiration(new Date(System.currentTimeMillis() + 1000 * 60 * 60 * 10))
Listo, hecho junto a nuestro "secret"

2021-11-01 14:17 UTC, Stdela commented on src/main/java/com/alkemy/ong/Controller/UserController.java
> +    public ResponseEntity<?> registerUser(@RequestBody Users appUser) {
Sí! En un principio era un pr para tener una corrección general y mostrar cómo pensaba que lo podíamos crear, pero me re sirve las delimitaciones que me marcaste como la creación del Token en sí.

2021-11-01 19:30 UTC, nicolascareri requested changes

2021-11-01 19:30 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +                .antMatchers(endpoint).permitAll()
Fijate que aca le podes pasar authroizedEndpoint derecho, si te deja removemos la linea 23.

2021-11-01 19:30 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +    String[] authorizedEndpoints = {"/auth/register", "/auth/log_in"};
Aca metele un enter asi queda mas legible, mas que nada para cuando vayamos agregando varias cosas

2021-11-01 19:30 UTC, nicolascareri commented on src/main/resources/application.properties
> +jwt.expiration = 1000 * 60 * 60 * 10
No esta bien que se haga un calculo aca. La idea es que aca se ponga el numero en segundos o miliseugndos de cuanto se quiere la expiracion y el resto lo manejas desde jwtTokenUtil.java

2021-11-02 16:00 UTC, nicolascareri requested changes

2021-11-02 16:00 UTC, nicolascareri commented on pom.xml
> +	 <dependency>
Tenes conflictos aca

2021-11-02 17:14 UTC, Stdela commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +        http.exceptionHandling()
Juntamos los puntos con Pablo, su review pedía que tire un 403 en caso de error en la autenticación y tenía entendido que así se hacía! Ahí lo saco

2021-11-02 17:32 UTC, Stdela commented on pom.xml
> +	 <dependency>
Perdón, no entendí esta corrección. Era un tema del Jar ?

2021-11-04 00:32 UTC, nicolascareri approved these changes

2021-11-04 00:32 UTC, merged