OT99-33 filter added
alkemyTech/OT-99-Server pull request #17
Opened 2021-10-30 02:26 UTC by pabloamado

REPORT:
JwtRequestFilter added

mocked roles:
![imagen](https://user-images.githubusercontent.com/54250734/139516797-e65c3dac-aa4b-4742-b72e-117b88ac1930.png)

mocked users:
![imagen](https://user-images.githubusercontent.com/54250734/139516841-0cd786da-ed47-4704-91f8-8a8d7129c1dc.png)

user with role user with correct id in token:
![imagen](https://user-images.githubusercontent.com/54250734/139516885-ff7903c0-9528-4659-9888-0c824f7dea47.png)
![imagen](https://user-images.githubusercontent.com/54250734/139516964-b1de2594-2fd0-47cf-a446-a196df3905b7.png)
![imagen](https://user-images.githubusercontent.com/54250734/139516982-d594e287-7632-4a9a-94b7-19a5850334fd.png)

user with role user with id incorrect (wrong id forced, the real user has id 1):
![imagen](https://user-images.githubusercontent.com/54250734/139517056-479cf7d1-b898-4749-aeb1-d68d1a9c338a.png)
Error expected:
![imagen](https://user-images.githubusercontent.com/54250734/139517118-c96a6793-2f12-4b15-a48d-822d330bbd3b.png)
messages expected:
![imagen](https://user-images.githubusercontent.com/54250734/139517126-91255032-7cf6-4a03-b147-17756fcb63c4.png)

user with role admin with incorrect id in token:
![imagen](https://user-images.githubusercontent.com/54250734/139517161-fccb2daa-e42b-4aef-911a-377b69d44493.png)
expected message:
![imagen](https://user-images.githubusercontent.com/54250734/139517226-c693ce5e-b5c5-426d-8a99-a0f5062d2eeb.png)
![imagen](https://user-images.githubusercontent.com/54250734/139517232-e4fbae1c-f821-4e21-ac11-f987beb126e8.png)

2021-10-31 21:41 UTC, nicolascareri approved these changes

2021-10-31 22:26 UTC, nicolascareri requested changes

2021-10-31 22:26 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
> +	private UserService userService;
El PR en general esta perfecto, pero no puedo mergear esto porque en master no existe el UserService ni el JwtTokenUtil (entiendo que esta en el otro PR). Pero si yo mergeo esto y otra persona se trae el codigo de master se le va a romper todo. Habria que ver como podemos solucinar esto, cualquier cosa lo vemos mañana en la daily

2021-11-01 13:17 UTC, pabloamado commented on src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
> +	private UserService userService;
queres que lo cambie por  user repository por el momento? el problema es que va a romper igual porque esa funcion no existia en el userRepository al momento en que se subio ese repositorio. Yo no me meti mano por las dudas porque no queria tocar codigo que no era mio.

2021-11-01 20:08 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
> +	private UserService userService;
Otra cosa que me di cuenta, que ni en este PR ni en el otro esta la parte de los ROLES

2021-11-01 20:33 UTC, pabloamado commented on src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
> +	private UserService userService;
esta cargado (me pedia que preguntase por el rol ADMIN) al validar el token:
 public Boolean validateToken(String token, Users user) {

        final Long id = Long.valueOf(extractId(token));

        return ((id == user.getId() && !isTokenExpired(token))
                || (user.getRol().getName().equalsIgnoreCase("ADMIN") && !isTokenExpired(token)));
    }

2021-11-01 20:41 UTC, pabloamado commented on src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
> +	private UserService userService;
perdon , me comi la firma de la funcion,
   public Boolean validateToken(String token, Users user) {

        final Long id = Long.valueOf(extractId(token));

        return ((id == user.getId() && !isTokenExpired(token))
                || (user.getRol().getName().equalsIgnoreCase("ADMIN") && !isTokenExpired(token)));
    }
     en este commit 
 https://github.com/alkemyTech/OT-99-Server/pull/16/commits/b3b65aa236aa63e243f23ba0eae6db834be4318d

2021-11-02 22:03 UTC, closed without merging