Added Comment class-rep-service
alkemyTech/OT-99-Server pull request #18
Opened 2021-11-01 18:29 UTC by Stdela

![image](https://user-images.githubusercontent.com/80407833/139722045-891848b3-d403-4a05-acfc-7c8740c5ec89.png)

-Created Comment class, repo, service and interface

2021-11-01 19:33 UTC, nicolascareri requested changes

2021-11-01 19:33 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/imp/CommentInterface.java
> +public interface CommentInterface {
Esto se deberia llamar CommentService y la implementacion "CommentServiceImpl"

2021-11-01 19:33 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/CommentService.java
> +public class CommentService implements CommentInterface{
CommentServiceImpl implements CommentService

2021-11-01 19:33 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/model/Comment.java
> +    @Lob
Yo no pondria esto, la historia no especifica que es binario, tranquilamente podria ser un String como un comentario de facebook me imagino

2021-11-02 16:02 UTC, nicolascareri requested changes

2021-11-02 16:02 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/CommentService.java
> +public interface CommentService {
Te quedo todo joya, pero te estaria faltando el repositorio

2021-11-02 17:04 UTC, Stdela commented on src/main/java/com/alkemy/ong/service/CommentService.java
> +public interface CommentService {
Uh, corregido

2021-11-03 18:47 UTC, nicolascareri approved these changes

2021-11-03 18:48 UTC, merged