Ot99 29 mail template
alkemyTech/OT-99-Server pull request #24
Opened 2021-11-04 03:49 UTC by pabloamado

### REPORT:
application properties updated (enviroment variables added)
pom.xml updated
class EmailTemplate added,
class EmailTemplateMessage added,
class EmailUtils added

### EVIDENCE:
Email sended with the Template:
![imagen](https://user-images.githubusercontent.com/54250734/140254457-47a0aae8-66a0-4ba1-b9ff-09edaa19d076.png)

the messages are part from the EmailTemplateMessage:
![imagen](https://user-images.githubusercontent.com/54250734/140254528-7796dd95-9544-4897-bbc8-39c0661748d1.png)

The email is prepared and sended by EmailUtils:
![imagen](https://user-images.githubusercontent.com/54250734/140254767-ca31a964-b0b0-4a80-81bd-bce8e5c740f3.png)

![imagen](https://user-images.githubusercontent.com/54250734/140254745-ee3b61fa-b9e5-46d2-a4ea-41baad1f0e14.png)

application properties:
![imagen](https://user-images.githubusercontent.com/54250734/140254898-e4a8f07c-613e-4474-965e-1427b015b7ee.png)

pom.xml:
![imagen](https://user-images.githubusercontent.com/54250734/140254945-510c2ba1-9827-43af-a2a3-a0f53acb3c4c.png)

2021-11-04 19:37 UTC, nicolascareri requested changes

2021-11-04 19:37 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/email/EmailTemplate.java
> +public String getPreparedBody(String tittleContent,String textContent,String mailContact,String cellContact) {
Lo mejor seria que todo este html este en un archivo html . Y lo puedas llamar .

Igual ojo porque solamente tenes que hacer el template. Porque la parte de configuracion o hacer servicio de email generico correspondia a otra historia. Fijate de hablar con tomi que es el que tiene la historia

2021-11-04 19:37 UTC, nicolascareri commented on src/main/resources/application.properties
> +API_SENDGRID_KEY=YOUR_SENDGRID_API_KEY
Aca deberiamos poner una real para que a todos les ande, no le veo sentido que cada uno se ande creando una cuenta de sendgrid

2021-11-04 21:00 UTC, pabloamado commented on src/main/resources/application.properties
> +API_SENDGRID_KEY=YOUR_SENDGRID_API_KEY
no se pueden subir las keys de sendgrid a github, te tira la key generada.

2021-11-04 21:26 UTC, pabloamado commented on src/main/java/com/alkemy/ong/email/EmailTemplate.java
> +public String getPreparedBody(String tittleContent,String textContent,String mailContact,String cellContact) {
consulta, pero entonces como hago para inyectarle los datos al html si el contenido esta en un archivo aparte y que no es un archivo java?
Con respecto a lo otro entonces deberia borrar la funcion  sendEmail correcto??

2021-11-05 18:14 UTC, nicolascareri approved these changes

2021-11-06 16:44 UTC, nicolascareri approved these changes

2021-11-06 16:44 UTC, merged