Ot99 40 category controller get all endpoint
alkemyTech/OT-99-Server pull request #25
Opened 2021-11-04 16:11 UTC by pabloamado

### REPORT:
package mapper added,
class CategoryController added,
class CategoryMapper added,
interface CategoryService added,
class CategoryServiceImpl added,
class categoryDtoGetAll added.
class UserRepository fixed (annotation repository added)

### EVIDENCE:
**The get endpoints to bring all the categories works (only the names):**
![imagen](https://user-images.githubusercontent.com/54250734/140376217-f5048878-3d3e-4eb0-9119-5b0298b20d1e.png)

2021-11-05 18:18 UTC, nicolascareri requested changes

2021-11-05 18:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +		return ResponseEntity.status(HttpStatus.OK).body(categories);
Es mucho mas legible y estandarizado devolver algo asi:
`return new ResponseEntity<>( categoryService.getAllCategories() , HttpStatus.OK );`

2021-11-05 18:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +		return ResponseEntity.status(HttpStatus.OK).body(categories);
te queda el controller de 1 linea

2021-11-05 18:18 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +			for(Category categ:categories) {
Aca se deberia hacer un map con lambda para efectuar el mapeo. Si tenes duda de como hacerlo avisame y lo vemos

2021-11-05 21:54 UTC, pabloamado commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +			for(Category categ:categories) {
no se como hacer lambdas D:

2021-11-06 02:31 UTC, pabloamado commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +			for(Category categ:categories) {
ya esta hecho, aprobame el PR !!!! jajaja

2021-11-06 16:50 UTC, nicolascareri requested changes

2021-11-06 16:50 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +			categories.stream().map(Category::getName).toList().forEach(i -> categoriesDto.add(new CategoryDtoGetAll(i)));
Se podria mejorar, porque volves a hacer una 2da iteracion con el foreach. En vez de hacer categoresDto.add() en un foreach. Deberias hacer algo asi:
`List<CategoryDtoGetAll> categoriesDto = categories.stream().map(category -> {
return new CategoryDtoGetAll(category.getName());
}).collect(Collectors.toList());`.
Osea haciendo esto ahces todo en una sola iteracion. Si tenes dudas avisame

2021-11-08 14:12 UTC, nicolascareri approved these changes

2021-11-08 14:12 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +			categoriesDto = categories.stream().map(category -> { return new CategoryDtoGetAll(category.getName()); }).collect(Collectors.toList());
esto esta joya. Cuando el lambda te queda de una sola linea como en este caso, los {} los podes remover. Es como la arrow function de javascript. Lo dejamos para la prox para que sepas

2021-11-08 14:13 UTC, nicolascareri approved these changes

2021-11-08 14:13 UTC, merged