OT99-42-Category-Endpoint-Creation
alkemyTech/OT-99-Server pull request #28
Opened 2021-11-06 18:06 UTC by ingrid-inga

![Category-creation](https://user-images.githubusercontent.com/75276647/140619163-6025df73-1c49-4056-bf1c-fbcfe67a8d5c.png)
![BadRequest](https://user-images.githubusercontent.com/75276647/140619179-b1af2660-01de-4542-827b-02e48b6fb440.png)

2021-11-06 21:09 UTC, nicolascareri requested changes

2021-11-06 21:09 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        categoryRepository.save(category);
el save del repositorio te devuelve la entidad tal cual como se persiste, deberiamos retornar esto en el servicio

2021-11-06 21:09 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +        return new ResponseEntity<>(categoryDto, HttpStatus.CREATED);
Aca estas devolviendo como repsonse exactamente lo mismo qeu te llego como request, la idea es que devuelvas lo que te retorna el servicio que seria la categoria que se persistio

2021-11-06 23:31 UTC, ingrid-inga commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +        return new ResponseEntity<>(categoryDto, HttpStatus.CREATED);
Hola!. ¡Muchas gracias por el feedback!, te refieres a todos los datos que se detallan en la entidad/Model?

2021-11-06 23:40 UTC, ingrid-inga commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +        return new ResponseEntity<>(categoryDto, HttpStatus.CREATED);
Hola!. ¡Muchas gracias por el feedback!, te refieres a utilizar save, en lugar de create, verdad?

2021-11-07 04:15 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +        return new ResponseEntity<>(categoryDto, HttpStatus.CREATED);
el controller debe retornar lo que devuelve el servicio y vos estas retornando el categoryDto tal cual te viene, a su vez el servicio, como te marque mas abajo, devuelve la entidad persistida. Si tenes dudas de como hacerlo avisame

2021-11-08 14:24 UTC, nicolascareri requested changes

2021-11-08 14:24 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/exception/ErrorHandler.java
> +        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
El NotFound deberia devolver un 404 not found, no un 400 bad request

2021-11-08 19:43 UTC, ingrid-inga commented
Category has been created.

![Screen Shot 2021-11-08 at 15 47 52](https://user-images.githubusercontent.com/75276647/140807076-4f02c4fe-62fc-4ae2-ba94-c3b8d06352fa.png)


Data Already exist.

![Screen Shot 2021-11-08 at 15 48 38](https://user-images.githubusercontent.com/75276647/140806560-7888bf4c-aa62-4ac0-b154-b303a2d568ec.png)

2021-11-08 20:23 UTC, nicolascareri requested changes

2021-11-08 20:23 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        categoryRepository.save(category);
Capaz me exprese mal Ingrid, pero el servicio en vez de retornar void deberia retornar la categoria creada, es decir deberias retornar lo que te devuelve el save

2021-11-08 20:23 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/exception/ErrorHandler.java
> +    public ResponseEntity<?> handleDataAlreadyExistException(HttpServletRequest request, DataAlreadyExistException e) {
Fijate que este metodo es exactamente igual al de handleEmailAlreadyExiste, ambos reciben un mensaje y devuelve badrequest. Si lo pensamos de manera abstracta o generica, se podria usar 1 solo porque hacen lo mismo. Tal vez estaria bueno cambiarle el nombre

2021-11-08 20:23 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +        return new ResponseEntity<>(categoryDto, HttpStatus.CREATED);
La idea es que devuelvas lo que se creo en el servicio. Es decir el controller debe retornar como response lo que te devuelve el servicio

2021-11-09 18:23 UTC, ingrid-inga commented
Changes not committed about paths: "/categories"

![Screen Shot 2021-11-09 at 15 09 46](https://user-images.githubusercontent.com/75276647/140980611-c2f3626a-fd78-434f-9bf5-081d841959e8.png)

Category created

![Screen Shot 2021-11-09 at 14 36 33](https://user-images.githubusercontent.com/75276647/140980662-4c863487-bcf4-4022-a172-7c8a594ad7e5.png)


Data already exist

![Screen Shot 2021-11-09 at 14 37 31](https://user-images.githubusercontent.com/75276647/140981949-30b0f6e3-af35-47ce-8c4c-c22678acac01.png)

2021-11-09 21:34 UTC, nicolascareri requested changes

2021-11-09 21:34 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        categoryRepository.save(category);
return categoryRepository.save(category);

2021-11-09 22:24 UTC, ingrid-inga commented
@nicolascareri  Ready!

2021-11-10 17:24 UTC, nicolascareri approved these changes

2021-11-10 17:24 UTC, merged