Ot99 55 endpoint slide list
alkemyTech/OT-99-Server pull request #34
Opened 2021-11-09 15:41 UTC by TomasFogwill

**Summary**

1. Added SlideService interface and implementation
2. Added SlideController
3. Created GET /slides endpoint which return the image url and slide order. Also created Dto as an inner class in the repository
4. Created service method that return from database the list of slides as entitys.

**Evidence**
sql: select*from slide;
![evidence](https://user-images.githubusercontent.com/83930746/140954359-b44ff97f-ed59-4cc6-9850-89628871f274.png)
localhost:8080/slides
![evidence1](https://user-images.githubusercontent.com/83930746/140955640-ffef962c-07d7-452d-8d34-5957aa759ffc.png)

2021-11-09 15:44 UTC, TomasFogwill commented
Nico armé esto de esta manera, con el dto como clase interna del controller, y mapeando usando una expresión lambda.Me pareció consiso y que respetaba lo pedido. Lo del mapeo en el repositorio lo saque de acá: https://www.baeldung.com/entity-to-and-from-dto-for-a-java-spring-application . Si no te parece que este bueno o querés que esté en la misma linea que hicieron los demás usando una clase mapper y otra clase dto, lo cambio

2021-11-10 15:55 UTC, nicolascareri requested changes

2021-11-10 15:55 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +        List<SlideDto> slideDtos = slides.stream().map(
Todo esto lo deberias hacer del servicio, y ya devolver la lista de slideDto, esta bien que hayas usado el map con el lambda. Lo que is subime el slideDto porque no esta en main y si lo mergeo se va a romper todo

2021-11-12 15:01 UTC, nicolascareri approved these changes

2021-11-12 15:01 UTC, merged