OT99-41-Endpoint-Category-Details
alkemyTech/OT-99-Server pull request #36
Opened 2021-11-10 16:56 UTC by ingrid-inga

================================Get by id.================================================

![Screen Shot 2021-11-10 at 13 16 32](https://user-images.githubusercontent.com/75276647/141157369-36be9e97-0370-4f0a-9d8c-205e981286a8.png)

================================404 Not Found.=========================================

![Screen Shot 2021-11-10 at 13 17 18](https://user-images.githubusercontent.com/75276647/141157400-3f76a182-2c97-4f68-a0be-40fc3a9bd308.png)

2021-11-10 17:29 UTC, nicolascareri requested changes
Solucionar conflictos

2021-11-10 17:29 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +			Category category = categoryMapper.dtoToEntity(id);
Estas mapeando una category y despues no la usas

2021-11-10 17:29 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +		   throw new NotFoundException("Wrong!, Category doesn't exist.");
yo en este caso usaria el orElseThrow que te provee el optional y te ahorras los IF y el ELSE

2021-11-10 22:44 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +			Category category = categoryMapper.dtoToEntity(id);
public Category getCategoryById(long id) throws NotFoundException {
  Category category = categoryRepository.findById(id).orElseThrow( ()-> NotFoundException("Wrong!, Category doesn't exist.")  );
return categoryMapper.entityToDto(category);
}

2021-11-10 22:44 UTC, nicolascareri requested changes

2021-11-10 22:44 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +	public Category dtoToEntity(long id) {
public CategoryDto EntityToDto (Category category) {
 CategoryDto categoryDto = modelMapper.map(category, CategoryDto.class);
 return categoryDto;
}

2021-11-11 03:49 UTC, ingrid-inga commented
****Se actualiza "Time" del código correspondiente a "Create" (Referencia: PR - OT99-42. Link: https://github.com/alkemyTech/OT-99-Server/pull/28) . Anda ok!.

![Screen Shot 2021-11-11 at 00 09 13](https://user-images.githubusercontent.com/75276647/141233247-276a9fcf-d9ec-434f-9aa4-d49f7f9e47a6.png)

=========================================================================================

*******Retorna los datos de la categoría creada by Id.

![Screen Shot 2021-11-11 at 00 10 03](https://user-images.githubusercontent.com/75276647/141233417-6dcfff4f-2996-4f6b-8385-bfd69cc5bca1.png)

2021-11-11 03:59 UTC, ingrid-inga reviewed
Double code in Error Handler. Updated.

2021-11-11 14:56 UTC, nicolascareri approved these changes

2021-11-11 14:56 UTC, merged