Ot99 48 endpoint delete news
alkemyTech/OT-99-Server pull request #37
Opened 2021-11-10 17:27 UTC by TomasFogwill

**Summary**

1. Added NewsRepository
2. Added NewsService interface
3. Added NewsServiceImpl implementation
4. Created endpoint DELETE /news/{id}
5. Created logic in service that do the soft delete and set the delete date
**Evidence**
sql: select*from news;
![evidence](https://user-images.githubusercontent.com/83930746/141162484-9ef1fd51-bc61-4a6d-8760-7cf92024d093.png)
![evidence1](https://user-images.githubusercontent.com/83930746/141162511-0b5c4279-bc07-4fbc-b90a-e6ca2a1147e0.png)
sql: select*from news; after calling the endpoint
![evidence3](https://user-images.githubusercontent.com/83930746/141162558-ffc96ccf-7470-47b4-96ff-c991722e06b3.png)
calling the enpoint again, we can see that, cause the soft delete, doesnt found a new
![evidence2](https://user-images.githubusercontent.com/83930746/141162715-1001e663-2294-4ce8-b9a5-dea62b0f05b7.png)

2021-11-10 21:33 UTC, nicolascareri requested changes

2021-11-10 22:33 UTC, nicolascareri requested changes

2021-11-10 22:33 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +           News news = newsRepository.findById(id).get();
usar orElseThrow

2021-11-10 22:33 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +    public boolean deleteNew(Long id) {
retornar void

2021-11-10 22:33 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +    @DeleteMapping("/:{id}")
el : esta demas

2021-11-11 17:45 UTC, TomasFogwill commented
![before1](https://user-images.githubusercontent.com/83930746/141344587-28ba24e1-dad2-4b3f-91bf-c23c3b5f81b9.png)
![before2](https://user-images.githubusercontent.com/83930746/141344603-c3beb177-cc4b-411b-95f3-cf084c7cebe4.png)
![deleting](https://user-images.githubusercontent.com/83930746/141344626-44e16445-113f-4bec-8a84-5ddefbb835ca.png)
![after1](https://user-images.githubusercontent.com/83930746/141344648-64aad3bb-7aef-45b5-9141-b6b68a540ed9.png)
![after2](https://user-images.githubusercontent.com/83930746/141344657-58f81bd0-3cd8-45b4-ac89-dc8d98a0f64c.png)
![metodo1](https://user-images.githubusercontent.com/83930746/141344669-cd85cb06-17ad-4b33-81d5-c136ee8ab6fb.png)
![metodo2](https://user-images.githubusercontent.com/83930746/141344686-968b019b-e9be-4469-9d4b-fb5e8272aebd.png)
![metodo3](https://user-images.githubusercontent.com/83930746/141344693-609e1306-0952-4a49-b36a-1a004e20f25a.png)

2021-11-13 19:37 UTC, nicolascareri approved these changes

2021-11-13 19:37 UTC, merged