OT99-38-Setup-Amazon-S3-Sdk
alkemyTech/OT-99-Server pull request #38
Opened 2021-11-10 21:00 UTC by ingrid-inga

==============================Post  Upload image================================

![url](https://user-images.githubusercontent.com/75276647/141191689-6fe5a5c2-9dfe-46e0-a803-5d8fb84c99b8.png)

=============================url response =========================================

![alkemyuploaded](https://user-images.githubusercontent.com/75276647/141191818-fed5d7de-b924-465e-b154-4414f3dd4237.png)

===========================Controller and Service created as a test, but not committed===============
![Screen Shot 2021-11-10 at 17 49 00](https://user-images.githubusercontent.com/75276647/141191850-a6595437-f86a-4174-afae-9bbd93fc720e.png)

2021-11-10 22:22 UTC, nicolascareri requested changes

2021-11-11 00:34 UTC, ingrid-inga commented
*Sobre las dependencias:


https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-project-maven.html
![Screen Shot 2021-11-10 at 21 30 10](https://user-images.githubusercontent.com/75276647/141215405-0617b018-cfce-40d5-ae55-f1a14888c257.png)

2021-11-11 14:57 UTC, nicolascareri requested changes

2021-11-11 14:57 UTC, nicolascareri commented on src/main/resources/application.properties
> +amazonProperties:
Ingrid , estas seguro que esto anda? fijate como estan las properties de sendgrid o de la base de datos y como estan las que pusiste vos, habria uqe revisarlo

2021-11-11 15:23 UTC, ingrid-inga commented on src/main/resources/application.properties
> +amazonProperties:
Hola!
Sí anda!
Copiando y pegando las credenciales.

2021-11-11 21:00 UTC, ingrid-inga reviewed
Listo!

2021-11-13 19:36 UTC, nicolascareri approved these changes

2021-11-13 19:36 UTC, merged