Ot99 14 return token to registered user
alkemyTech/OT-99-Server pull request #42
Opened 2021-11-11 14:29 UTC by TomasFogwill

**Summary**

1. Added String jwt field in UserRegisterResponse
2. Created methods to create jwt and map the dto

**Evidence**

![evidence](https://user-images.githubusercontent.com/83930746/141315036-79b1f5d1-55cf-4084-8370-4784db9c405a.png)
![evidence2](https://user-images.githubusercontent.com/83930746/141315061-89b07ed6-8992-45e8-81e6-148e213cbce8.png)

2021-11-11 14:32 UTC, TomasFogwill commented
Un par de detalles que encontre. Primero, cuando uno se registra y repite algunos datos que ya uso algun usuario previamente, pero que no tendrian por que dar problema, creo que la url de la foto o el password, se guarda el usuario en la base de datos, pero devuelve un status 500. Por otro lado, no se si estará mal hecho mi método de calcular el jwt, porque no me autorizaba a entrar a ningun endpoint, siempre dandome status 403. De ser que yo hice todo bien, igual habría que revisar estas cosas más adelante.

2021-11-11 15:08 UTC, nicolascareri commented
> Un par de detalles que encontre. Primero, cuando uno se registra y repite algunos datos que ya uso algun usuario previamente, pero que no tendrian por que dar problema, creo que la url de la foto o el password, se guarda el usuario en la base de datos, pero devuelve un status 500. Por otro lado, no se si estará mal hecho mi método de calcular el jwt, porque no me autorizaba a entrar a ningun endpoint, siempre dandome status 403. De ser que yo hice todo bien, igual habría que revisar estas cosas más adelante.

Deberias resolver los 403 o los 500 antes de subir el PR, si ves que no podes , lo podes revisar conmigo

2021-11-11 15:10 UTC, nicolascareri requested changes
revisar 403 o 500. LEER COMENTARIO MIO en la solapa de overview

2021-11-11 15:10 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    public ResponseEntity<List<SlideDto>> getAllCategories() {
esto es de otro PR...

2021-11-11 15:10 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +        Authentication auth = authenticationManager
Estas repitiendo codigo, si creaste un metodo privado para obtener el token lo deberias usar aca tambien

2021-11-11 15:16 UTC, TomasFogwill commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +        Authentication auth = authenticationManager
Armé ese método privado, pero como esa funcionalidad la hizo otro compañero, no la quise tocar

2021-11-13 19:36 UTC, nicolascareri approved these changes

2021-11-13 19:36 UTC, merged