Ot99 56 slide get endpoint
alkemyTech/OT-99-Server pull request #44
Opened 2021-11-12 12:25 UTC by pabloamado

REPORT:
Classes SlideService and SlideServiceImpl added  (with getSlide method)
Added EntityNotFoundException to ErrorHandler 
fix introduced in class userServiceImpl in method findByEmail (needed the annotation @Transactional and to load the role because the lazy fetch)
added strings in class SecurityConfiguration (for the admin role)
fix in jwtTokenUtil, change inserted in method validateToken (the  string to compare the role changed from "admin" to "ROLE_ADMIN")

First Scenario, role USER introduced in Database to test:
![imagen](https://user-images.githubusercontent.com/54250734/141463665-879d1586-791a-4474-9246-ce73313e7844.png)

because we need it at the moment of the register because this:
![imagen](https://user-images.githubusercontent.com/54250734/141463793-b34450dc-093b-4947-8d2b-57be742ecbb7.png)

we create an slide in database:
![imagen](https://user-images.githubusercontent.com/54250734/141464612-1f9c7ffd-9fe4-4848-8c27-014fe1cc631f.png)

Changed needed in SecurityConfiguration:
![imagen](https://user-images.githubusercontent.com/54250734/141466749-7f710ac4-c31b-424f-9fb3-03a0db7c0377.png)

After register, and login, we test the error, because a USER role can access:
register:
![imagen](https://user-images.githubusercontent.com/54250734/141465019-a0433614-e707-48b0-832f-d7586e7507ca.png)

changed needed in userServiceImpl for the register:
![imagen](https://user-images.githubusercontent.com/54250734/141465121-e1e15e20-57e1-44a0-ab3e-b1ccf941fb6e.png)

we logged in and test the forbidden endpoint for USER ROLE:
![imagen](https://user-images.githubusercontent.com/54250734/141465361-bf4fa7ad-a084-4233-9605-093ace8979b8.png)

Second scenario the user  has ADMIN ROLE:
we changed the role in the database:
![imagen](https://user-images.githubusercontent.com/54250734/141466124-0316d131-41aa-4553-8914-d32e7bd523a1.png)

and test the endpoint  for AN EXISTING SLIDE WITH ID 1:
![imagen](https://user-images.githubusercontent.com/54250734/141466344-64942865-83f5-4796-b26c-0f5418ed2c11.png)

test the endpoint again to pop the error FOR INEXISTENCE OF SLIDE WITH ID 2:
![imagen](https://user-images.githubusercontent.com/54250734/141466515-74436a36-4d97-4f5e-9c15-ee36f86e585b.png)

2021-11-12 12:35 UTC, pabloamado commented
Buenas Nicolas, de acuerdo al ticket, como tenia que testear el endpoint como administrador, descubri un pequeño bug en el metodo findByEmail del userServiceImpl, realice una carga del Rol del usuario porque tenia fetchLazy (generando la caida del programa) y una clausula if necesaria para el registro de usuario(porque tambien se caia el programa al preguntar si habia un usuario ya registrado con ese mail).
Por otro lado agregue los endpoints en la clase SecurityConfiguration en el array de strings:  /slide/{id} y /categories (este ultimo me habia olvidado de agregarlo del ticket pasado porque tambien era de uso del administrador y  lo testie sin uso de roles, grave error mio).
Por otro lado agregue un error personalizado para lanzar el error 404 pedido por el ticket.

2021-11-12 16:58 UTC, nicolascareri requested changes

2021-11-12 16:58 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +        if(user!=null) user.getRole().getName();
esta linea esta rara porque le pedis el getName pero no haces nada con eso

2021-11-12 21:48 UTC, pabloamado commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +        if(user!=null) user.getRole().getName();
por el lazy fetch del rol, necesito cargarlo porque sino  se cae la  aplicacion, a la hora de necesitarlo en el filtro apunta  a un nulo sino.

2021-11-13 19:32 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +        if(user!=null) user.getRole().getName();
ahi le sacamos el lazy con ingrid ya te deberia andar sin esa linea, probalo devuelta y si no lo dejamos

2021-11-13 19:33 UTC, nicolascareri approved these changes

2021-11-13 19:35 UTC, nicolascareri requested changes

2021-11-13 19:35 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/exception/ErrorHandler.java
> +	protected ResponseEntity<?> nombreDelMetodo(EntityNotFoundException e, WebRequest webRequest){
nombreDelMetodo?

2021-11-13 19:35 UTC, nicolascareri requested changes

2021-11-13 19:35 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +  public ResponseEntity<List<SlideDto>> getAllCategories() {
ya se que no es tuyo pero podrias cambiarle el nombre al metodo por uno mas representativo?

2021-11-13 21:02 UTC, pabloamado commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +        if(user!=null) user.getRole().getName();
okas, ahi hago un pull y modifico

2021-11-13 21:02 UTC, pabloamado commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +  public ResponseEntity<List<SlideDto>> getAllCategories() {
dale

2021-11-13 21:03 UTC, pabloamado commented on src/main/java/com/alkemy/ong/exception/ErrorHandler.java
> +	protected ResponseEntity<?> nombreDelMetodo(EntityNotFoundException e, WebRequest webRequest){
pifie mio

2021-11-14 00:33 UTC, nicolascareri requested changes
bro se te enquilombo el PR tenes commits y archivos que no son tuyos

2021-11-14 00:44 UTC, pabloamado commented
ahi se resolvio me parece, me tiraba conflicto con el securityConfiguration, es que hice un pull de main porque iba muy atras mi rama y necesitaba ver si algo de eso podia afectar el pr.

2021-11-14 20:55 UTC, nicolascareri approved these changes

2021-11-14 20:55 UTC, merged