Ot99-52 Add Seed Organization Data
alkemyTech/OT-99-Server pull request #56
Opened 2021-11-16 22:37 UTC by Stdela

![image](https://user-images.githubusercontent.com/80407833/142077188-321861a6-b569-472d-a3df-50d5db089081.png)
- Added Seed data in root that populates database.organization. 
- Created using drive data, took some liberties at the time of writing welcome text and about us text.

2021-11-18 14:24 UTC, nicolascareri requested changes

2021-11-18 14:24 UTC, nicolascareri commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
creo que este no hace falta, con el de arriba ya es suficiente

2021-11-19 15:15 UTC, Stdela commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
Sin ese no anda jaja

2021-11-19 17:20 UTC, nicolascareri requested changes

2021-11-19 17:20 UTC, nicolascareri commented on src/main/resources/data.sql
> +REPLACE INTO organization(id,ORG_NAME, ORG_IMAGE_URL, ORG_ADDRESS, ORG_PHONE, ORG_EMAIL, ORG_WELCOME_TEXT, ORG_ABOUT_US_TEXT, IS_DELETED, LAST_UPDATE_DATE, CREATION_DATE )
esto esta joya, pero dejamelo mas lindo tabulado, metele unos enters, asi como esta es ilegible

2021-11-19 17:20 UTC, nicolascareri commented on src/main/resources/data.sql
> +REPLACE INTO organization(id,ORG_NAME, ORG_IMAGE_URL, ORG_ADDRESS, ORG_PHONE, ORG_EMAIL, ORG_WELCOME_TEXT, ORG_ABOUT_US_TEXT, IS_DELETED, LAST_UPDATE_DATE, CREATION_DATE )
esto incluye los values

2021-11-19 21:15 UTC, nicolascareri approved these changes

2021-11-19 21:16 UTC, merged