Ot99 72 user seeder
alkemyTech/OT-99-Server pull request #61
Opened 2021-11-18 01:49 UTC by pabloamado

### REPORT:
changes added in application.properties to insert default data in database
file data.sql added. Script that contains default values of users and roles to load.

Roles:
![imagen](https://user-images.githubusercontent.com/54250734/142336276-31e4aa55-6fc9-4f55-a55e-a8c31a872317.png)

Users with role admin:
![imagen](https://user-images.githubusercontent.com/54250734/142336315-b0dc951b-50c9-40e2-ad56-dde6d146f20d.png)

Users with role user:
![imagen](https://user-images.githubusercontent.com/54250734/142336337-8c53c084-8166-4726-a7b0-c6bdc04b0ecc.png)

proof after execute the program:
![imagen](https://user-images.githubusercontent.com/54250734/142336380-7b6ac331-47e4-415e-8a3a-54c1ec56e34b.png)
![imagen](https://user-images.githubusercontent.com/54250734/142336463-b0afb5cf-3b01-4952-9521-d6f460bf5fd5.png)

2021-11-18 14:36 UTC, nicolascareri requested changes

2021-11-18 14:36 UTC, nicolascareri commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
este creo que no hace falta

2021-11-18 14:36 UTC, nicolascareri commented on src/main/resources/data.sql
> +INSERT INTO users (creation_date,delete_date,deleted,email,first_name,last_name,last_update,password,photo, id_role) values
Aca nunca estas chequeando que existan o no. Por ende cada vez que levantes la aplicaicon te va insertar todo esto y vas a tener data repetida. Deberiamos agregar estos chequeos . Si tenes dudas de como resolverlo avisame

2021-11-20 01:00 UTC, pabloamado commented
Buenas Nico otra vez aparecieron los commits fantasmas,  tengo el historial ahora de lo que hice:
![imagen](https://user-images.githubusercontent.com/54250734/142708485-248856df-3a04-41e0-9f13-45a38a05045b.png)
![imagen](https://user-images.githubusercontent.com/54250734/142708516-f723439e-09f3-4bc6-a41e-de7815a974dd.png)
![imagen](https://user-images.githubusercontent.com/54250734/142708548-0b0b5f02-aba6-4aef-bba5-6934acdd01dc.png)
![imagen](https://user-images.githubusercontent.com/54250734/142708563-31ebe218-0184-4532-bae6-57129742ba00.png)

2021-11-20 18:06 UTC, nicolascareri commented
creo que es porque no agregaste todo y fuiste agregando por archivo

2021-11-22 17:10 UTC, nicolascareri requested changes

2021-11-22 17:10 UTC, nicolascareri commented on src/main/resources/data.sql
> +    (1,current_timestamp(),NULL,0,"mariano@gmail.com","Mariano","Forte",current_timestamp(),"123456","images/1.jpg",1),
Pablo fijate que cuando nos logeamos hacemos un match con la password hasheada, habria que ver si no conviene en vez de 123456 , hashearlo y persistir eso directamente. Asi queda como si fuera un registro real

2021-11-22 18:40 UTC, pabloamado commented
usuarios registrados, el hash no causa problemas:
![imagen](https://user-images.githubusercontent.com/54250734/142916366-092d75f6-d820-4a11-9f08-00558c18c839.png)
![imagen](https://user-images.githubusercontent.com/54250734/142916889-9f5b47cc-37db-46a1-abd8-0c8b685516ce.png)
algunos endpoints:
![imagen](https://user-images.githubusercontent.com/54250734/142916984-558df135-3faa-4ff8-90b0-612df893aefa.png)
![imagen](https://user-images.githubusercontent.com/54250734/142917101-0166ff68-b267-4280-a022-6c8535456485.png)

2021-11-22 20:44 UTC, nicolascareri approved these changes

2021-11-22 20:44 UTC, merged