OT99-69-Members-Endpoint-Creation
alkemyTech/OT-99-Server pull request #62
Opened 2021-11-18 11:44 UTC by ingrid-inga

POST: Member created!

![Screen Shot 2021-11-18 at 08 17 33](https://user-images.githubusercontent.com/75276647/142408944-1a92d1d3-79ed-4cb7-96dd-bbf8dffc3b66.png)

=====================================================================================

Not again!. Member already exists!.

![Screen Shot 2021-11-18 at 08 18 42](https://user-images.githubusercontent.com/75276647/142408908-5c77858d-0087-4dd5-ab19-bcd550d14fc0.png)

===================================================================================

Name is mandatory!

![Screen Shot 2021-11-18 at 08 19 24](https://user-images.githubusercontent.com/75276647/142408917-38dc5dac-d9ae-4d38-bc31-8aa7f7f56920.png)

=====================================================================================

Name can't be null!

![Screen Shot 2021-11-18 at 08 21 47](https://user-images.githubusercontent.com/75276647/142408925-43c57d0e-6b6d-42e1-a3e3-72a2687892b8.png)

2021-11-18 14:39 UTC, nicolascareri requested changes

2021-11-18 14:39 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +    private MemberService service;
la variable se deberia llamar memberService, tratemos de usar nombres mas representativos

2021-11-18 14:39 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/dto/MemberDto.java
> +    @NotBlank(message = "Name is mandatory.")
Se me paso en otro PR pero googlea la diferencia entre el NotBlank y el NotNull. Me parece que el notblank internamente ya chequea que no sea nulo, por ende con este solo bastaria

2021-11-18 14:39 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
> +    MemberRepository repo;
memberRepository se deberia llamar. Lo mismo que con el servicio del controller

2021-11-18 16:27 UTC, ingrid-inga commented
=================Changes============
![Screen Shot 2021-11-18 at 13 19 36](https://user-images.githubusercontent.com/75276647/142455430-177cc110-627a-4ef6-8cbc-343e56bc2fca.png)


===========Still working=======================
![Screen Shot 2021-11-18 at 13 16 15](https://user-images.githubusercontent.com/75276647/142455451-5d67b00e-8c10-410f-8a81-044ac0e10a61.png)

2021-11-19 13:50 UTC, nicolascareri approved these changes

2021-11-19 13:51 UTC, merged