Swagger-Security
alkemyTech/OT-99-Server pull request #69
Opened 2021-11-22 01:23 UTC by ingrid-inga

****Se agregaron líneas de código para que pueda habilitarse la opción de agregar el "Token" para así poder acceder a los endpoints.

![Screen Shot 2021-11-21 at 09 55 06](https://user-images.githubusercontent.com/75276647/142787432-4a122999-b53e-4be0-80e4-ce271b8bb99e.png)

Funciona!.
![Screen Shot 2021-11-21 at 22 01 15](https://user-images.githubusercontent.com/75276647/142787439-40bfdf5a-2570-4d2a-9b84-c52059b74384.png)

=========================================================================================

Está pendiente de solucionar un pequeño inconveniente con el endpoint "Get/auth/me". Agradezco sugerencias por favor. ¡Muchas Gracias!.

![Screen Shot 2021-11-21 at 22 03 15](https://user-images.githubusercontent.com/75276647/142787447-1d69781d-675f-437a-9c61-a6d9a9e4957d.png)

![Screen Shot 2021-11-21 at 22 04 09](https://user-images.githubusercontent.com/75276647/142787437-90c1370e-f5ea-4d36-b759-c9581ebbf085.png)

2021-11-22 17:14 UTC, nicolascareri commented
Esta todo bien, habria que resolver conflictos

2021-11-22 17:50 UTC, ingrid-inga commented
Listo!

2021-11-22 18:18 UTC, nicolascareri approved these changes

2021-11-22 20:44 UTC, nicolascareri requested changes

2021-11-23 15:16 UTC, ingrid-inga commented
****Intentando acceder de manera "anónima"(sin registro/sin login)

![Screen Shot 2021-11-23 at 00 04 57](https://user-images.githubusercontent.com/75276647/143048576-5de2004d-2c23-4054-bfcf-b8c794c38044.png)



===============================================================

Accediendo como USER 
********Importante!!!!!---> Colocar : Bearer ...... ***********************************===========

![Screen Shot 2021-11-23 at 10 52 15](https://user-images.githubusercontent.com/75276647/143047810-ead16ee2-e9cc-4427-bed8-cc7eb007fc5e.png)

=================AUTH/ME=================================

![Screen Shot 2021-11-23 at 10 49 07](https://user-images.githubusercontent.com/75276647/143049798-722055cb-34ce-42e1-8b55-549d291e5675.png)



![Screen Shot 2021-11-23 at 10 47 13](https://user-images.githubusercontent.com/75276647/143048554-4046c0a4-446b-4359-8495-48868951114d.png)


==========================================================================

Accediendo como ADMIN

![Screen Shot 2021-11-23 at 10 57 19](https://user-images.githubusercontent.com/75276647/143048596-1dcc4079-d283-404e-be50-1363c5b59921.png)


====================AUTH/ME===============================
![Screen Shot 2021-11-23 at 12 12 59](https://user-images.githubusercontent.com/75276647/143050666-7cc32a99-8ad5-499c-8a1e-d8a49d9bc640.png)

2021-11-23 15:20 UTC, ingrid-inga commented
*******Se modificaron líneas de código, se agregó Security Context; ahora se obtiene la información del usuario(login). 
**Las personas no estén registradas, no pueden acceder a los endpoints.
**Se agregó en el SecurityConfig una opción que permita agregar endpoints independientes, a fin de que pueda asignarse el acceso al USER y/o ADMIN.

2021-11-23 16:00 UTC, nicolascareri requested changes

2021-11-23 16:00 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +                .antMatchers(HttpMethod.POST, "/news").hasRole("ADMIN")
Esto no estaria bien porque estamos repitiendo lineas de codigo

2021-11-23 16:00 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +                .antMatchers(HttpMethod.POST, "/news").hasRole("ADMIN")
por algo creamos el arreglo con post y put para las rutas de admin

2021-11-23 16:19 UTC, nicolascareri approved these changes

2021-11-23 16:19 UTC, merged