OT99-82-Add-paging-members
alkemyTech/OT-99-Server pull request #75
Opened 2021-11-24 22:07 UTC by ingrid-inga

=========Solicitamos que se muestre la info de a 2=========================

![Screen Shot 2021-11-24 at 18 48 13](https://user-images.githubusercontent.com/75276647/143318216-2fdf10ad-d883-4d0b-b5c2-42f26c2d53e0.png)

![Screen Shot 2021-11-24 at 18 50 01](https://user-images.githubusercontent.com/75276647/143318228-d80813dc-6810-4944-9de5-24c1f428b68a.png)

==============Solicitamos que se muestre la info de a 5====================

![Screen Shot 2021-11-24 at 18 54 43](https://user-images.githubusercontent.com/75276647/143318250-bbe53aac-2b02-4d71-ad78-52210b1d9186.png)

![Screen Shot 2021-11-24 at 18 52 01](https://user-images.githubusercontent.com/75276647/143318240-accd5bb4-c9ee-4357-afd2-7a9559b8847a.png)

![Screen Shot 2021-11-24 at 18 53 01](https://user-images.githubusercontent.com/75276647/143318248-56fbd33e-10aa-4f2d-b205-1b4e38efc6a0.png)

2021-11-25 22:16 UTC, nicolascareri requested changes
Agregar pagina siguiente y anterior

2021-11-30 01:31 UTC, ingrid-inga commented
Previous and next Page added.

![Screen Shot 2021-11-29 at 22 03 38](https://user-images.githubusercontent.com/75276647/143969218-b0f0207a-11f4-4bde-ae8d-be91f3d9db18.png)


![Screen Shot 2021-11-29 at 22 04 33](https://user-images.githubusercontent.com/75276647/143969239-e5463272-383b-4a43-9d78-1cabecfcc339.png)

2021-11-30 21:33 UTC, nicolascareri approved these changes

2021-11-30 21:33 UTC, nicolascareri commented on src/main/java/com/alkemy/ong/controller/MemberController.java
> +       // List<Member> list = memberService.getAllMembers(pageNo, pageSize, sortBy);
remover linea

2021-11-30 21:45 UTC, merged